"""
Bill summarization using LLM.

This module implements bill summarization with LLM analysis,
integrating with Phase 1's LLMAnalyzer and CitationVerifier.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class BillSummary(BaseModel):
    """Summary of a bill generated by LLM."""

    bill_number: str
    title: str
    summary: str = Field(..., description="Main summary of the bill")
    key_provisions: list[str] = Field(
        default_factory=list, description="Key provisions of the bill"
    )
    objectives: list[str] = Field(default_factory=list, description="Objectives of the bill")
    affected_parties: list[str] = Field(
        default_factory=list, description="Parties affected by the bill"
    )
    implementation_timeline: Optional[str] = None
    budget_implications: Optional[str] = None
    citations: list[dict] = Field(
        default_factory=list, description="Verified citations in the summary"
    )
    model: str = Field(default="claude-3.5-sonnet", description="Model used for summarization")
    cost_usd: float = Field(default=0.0, description="Cost of LLM call in USD")
    generated_at: datetime = Field(default_factory=datetime.now)


@dataclass
class BillSummarizationRequest:
    """Request for bill summarization."""

    bill_number: str
    bill_text: str
    title: str
    chamber: str
    include_implementation: bool = True
    include_budget: bool = True


class BillSummarizer:
    """
    Summarizer for parliamentary bills using LLM.

    This class integrates with Phase 1's LLMAnalyzer and CitationVerifier
    to provide comprehensive bill summaries.

    Example:
        >>> summarizer = BillSummarizer(llm_analyzer, citation_verifier, cost_manager)
        >>> summary = summarizer.summarize_bill(bill_text, "5/2023", "Agriculture Bill")
    """

    def __init__(self, llm_analyzer, citation_verifier=None, cost_manager=None):
        """
        Initialize bill summarizer.

        Args:
            llm_analyzer: Phase 1 LLMAnalyzer instance
            citation_verifier: Optional CitationVerifier for verifying claims
            cost_manager: Optional CostManager for tracking costs
        """
        self.llm_analyzer = llm_analyzer
        self.citation_verifier = citation_verifier
        self.cost_manager = cost_manager
        self.logger = self._get_logger()

    def _get_logger(self):
        """Get logger instance."""
        import logging

        return logging.getLogger(self.__class__.__name__)

    def summarize_bill(
        self,
        bill_text: str,
        bill_number: str,
        title: str,
        chamber: str = "NATIONAL_ASSEMBLY",
        include_implementation: bool = True,
        include_budget: bool = True,
    ) -> BillSummary:
        """
        Summarize a bill using LLM.

        Args:
            bill_text: Full text of the bill
            bill_number: Bill number (e.g., "5/2023")
            title: Bill title
            chamber: Chamber name
            include_implementation: Whether to include implementation timeline
            include_budget: Whether to include budget implications

        Returns:
            BillSummary object with generated summary

        Raises:
            ValueError: If bill_text is empty or LLM analysis fails
        """
        if not bill_text or len(bill_text.strip()) == 0:
            raise ValueError("Bill text cannot be empty")

        # Build prompt
        prompt = self._build_prompt(
            bill_text,
            bill_number,
            title,
            chamber,
            include_implementation,
            include_budget,
        )

        # Call LLM analyzer
        try:
            analysis_result = self.llm_analyzer.analyze(
                text=bill_text,
                prompt=prompt,
                context_type="bill",
            )
        except Exception as e:
            raise ValueError(f"LLM analysis failed: {e}") from e

        # Parse response
        summary_data = self._parse_response(analysis_result, bill_number, title, bill_text)

        # Verify citations if verifier available
        if self.citation_verifier and summary_data.get("citations"):
            summary_data["citations"] = self._verify_citations(summary_data["citations"], bill_text)

        # Track cost
        cost = analysis_result.get("cost_usd", 0.0) if isinstance(analysis_result, dict) else 0.0
        if self.cost_manager:
            self.cost_manager.track_usage(
                model="claude-3.5-sonnet",
                input_tokens=len(bill_text.split()),
                output_tokens=len(summary_data.get("summary", "").split()),
                cost_usd=cost,
            )

        return BillSummary(
            bill_number=bill_number,
            title=title,
            summary=summary_data.get("summary", ""),
            key_provisions=summary_data.get("key_provisions", []),
            objectives=summary_data.get("objectives", []),
            affected_parties=summary_data.get("affected_parties", []),
            implementation_timeline=summary_data.get("implementation_timeline"),
            budget_implications=summary_data.get("budget_implications"),
            citations=summary_data.get("citations", []),
            cost_usd=cost,
        )

    def _build_prompt(
        self,
        bill_text: str,
        bill_number: str,
        title: str,
        chamber: str,
        include_implementation: bool,
        include_budget: bool,
    ) -> str:
        """
        Build prompt for LLM summarization.

        Args:
            bill_text: Full bill text
            bill_number: Bill number
            title: Bill title
            chamber: Chamber name
            include_implementation: Include timeline
            include_budget: Include budget info

        Returns:
            Formatted prompt for LLM
        """
        prompt = f"""Summarize the following bill from the {chamber}:

Bill Number: {bill_number}
Title: {title}

BILL TEXT:
{bill_text[:3000]}...

Please provide:

1. **Main Summary**: A 2-3 sentence overview of the bill
2. **Key Provisions**: 3-5 main provisions of the bill
3. **Objectives**: The main objectives this bill seeks to achieve
4. **Affected Parties**: Who will be affected by this bill
"""

        if include_implementation:
            prompt += "\n5. **Implementation Timeline**: When and how will this be implemented?"

        if include_budget:
            prompt += "\n6. **Budget Implications**: Any financial impacts mentioned?"

        prompt += """
7. **Important Claims**: List any specific claims, statistics, or facts

Format your response as structured text that can be parsed."""

        return prompt

    def _parse_response(
        self, analysis_result, bill_number: str, title: str, bill_text: str
    ) -> dict:
        """
        Parse LLM response into structured data.

        Args:
            analysis_result: Result from LLMAnalyzer
            bill_number: Bill number
            title: Bill title
            bill_text: Original bill text

        Returns:
            Dictionary with parsed summary data
        """
        # Extract text from analysis result
        if isinstance(analysis_result, dict):
            response_text = analysis_result.get("summary", "") or analysis_result.get("text", "")
        else:
            response_text = str(analysis_result)

        # Parse sections
        summary_data = {
            "bill_number": bill_number,
            "title": title,
            "summary": self._extract_section(response_text, "Main Summary", 2),
            "key_provisions": self._extract_list_section(response_text, "Key Provisions", 5),
            "objectives": self._extract_list_section(response_text, "Objectives", 3),
            "affected_parties": self._extract_list_section(response_text, "Affected Parties", 3),
            "implementation_timeline": self._extract_section(
                response_text, "Implementation Timeline"
            ),
            "budget_implications": self._extract_section(response_text, "Budget Implications"),
            "citations": self._extract_claims(response_text, bill_text),
        }

        return summary_data

    def _extract_section(self, text: str, section_name: str, sentences: int = 1) -> str:
        """
        Extract a section from response text.

        Args:
            text: Full response text
            section_name: Name of section to extract
            sentences: Number of sentences to extract

        Returns:
            Extracted section text
        """
        import re

        # Find section
        pattern = rf"\*\*{section_name}\*\*:?\s*(.+?)(?=\*\*|$)"
        match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)

        if match:
            section_text = match.group(1).strip()
            # Limit to specified number of sentences
            if sentences > 0:
                sents = section_text.split(".")[:sentences]
                return ". ".join(sents).strip() + "."
            return section_text[:200]

        return ""

    def _extract_list_section(self, text: str, section_name: str, max_items: int = 5) -> list:
        """
        Extract a list section from response text.

        Args:
            text: Full response text
            section_name: Name of section to extract
            max_items: Maximum items to extract

        Returns:
            List of extracted items
        """
        import re

        # Find section
        pattern = rf"\*\*{section_name}\*\*:?\s*(.+?)(?=\*\*|$)"
        match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)

        if match:
            section_text = match.group(1).strip()

            # Extract list items (numbers, bullets, or natural breaks)
            items = []
            for line in section_text.split("\n"):
                line = line.strip()
                if line and len(line) > 3:
                    # Remove bullet points and numbers
                    line = re.sub(r"^[\d\-\*•]\.\s*", "", line).strip()
                    if line:
                        items.append(line)
                        if len(items) >= max_items:
                            break

            return items

        return []

    def _extract_claims(self, text: str, bill_text: str) -> list:
        """
        Extract claims for citation verification.

        Args:
            text: LLM response text
            bill_text: Original bill text

        Returns:
            List of claims with citation info
        """
        import re

        claims = []

        # Look for "Important Claims" section
        pattern = r"\*\*Important Claims\*\*:?\s*(.+?)(?=\*\*|$)"
        match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)

        if match:
            claims_text = match.group(1).strip()

            for line in claims_text.split("\n"):
                line = line.strip()
                if line and len(line) > 5:
                    claims.append(
                        {
                            "claim": line,
                            "verified": False,
                            "source": None,
                        }
                    )

        return claims[:5]  # Limit to 5 claims

    def _verify_citations(self, citations: list, bill_text: str) -> list:
        """
        Verify citations using CitationVerifier.

        Args:
            citations: List of citations to verify
            bill_text: Original bill text

        Returns:
            Citations with verification results
        """
        for citation in citations:
            try:
                verified = self.citation_verifier.verify_claim(
                    claim=citation["claim"],
                    context=bill_text,
                )
                citation["verified"] = verified.get("verified", False)
                citation["confidence"] = verified.get("confidence", 0.0)
            except Exception as e:
                self.logger.warning(f"Citation verification failed: {e}")

        return citations

    def summarize_batch(
        self,
        bills: list[dict],
        include_implementation: bool = True,
        include_budget: bool = True,
    ) -> list[BillSummary]:
        """
        Summarize multiple bills.

        Args:
            bills: List of bill dictionaries with keys:
                  bill_number, bill_text, title, chamber
            include_implementation: Include timeline
            include_budget: Include budget info

        Returns:
            List of BillSummary objects
        """
        summaries = []

        for bill in bills:
            try:
                summary = self.summarize_bill(
                    bill_text=bill["bill_text"],
                    bill_number=bill["bill_number"],
                    title=bill["title"],
                    chamber=bill.get("chamber", "NATIONAL_ASSEMBLY"),
                    include_implementation=include_implementation,
                    include_budget=include_budget,
                )
                summaries.append(summary)
            except Exception as e:
                self.logger.error(f"Failed to summarize bill {bill['bill_number']}: {e}")

        return summaries
