"""Initial schema

Revision ID: 16b7b7b50c3c
Revises: 
Create Date: 2026-01-28 10:08:31.805970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b7b7b50c3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('HANSARD', 'VOTES', 'BILL', 'QUESTION', 'PETITION', 'STATEMENT_TRACKER', 'MOTION_TRACKER', 'BILL_TRACKER', 'ORDER_PAPER', 'LEGISLATIVE_PROPOSAL', 'AUDITOR_REPORT', name='documenttypeenum'), nullable=False),
    sa.Column('chamber', sa.Enum('NATIONAL_ASSEMBLY', 'SENATE', name='chamberenum'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('parliament_term', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('download_date', sa.DateTime(), nullable=False),
    sa.Column('vector_doc_id', sa.String(length=100), nullable=False),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash')
    )
    op.create_index('idx_documents_date', 'documents', ['date'], unique=False)
    op.create_index('idx_documents_source_hash', 'documents', ['source_hash'], unique=False)
    op.create_index('idx_documents_type_chamber_date', 'documents', ['type', 'chamber', 'date'], unique=False)
    op.create_table('mps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('chamber', sa.Enum('NATIONAL_ASSEMBLY', 'SENATE', name='chamberenum'), nullable=False),
    sa.Column('party', sa.String(length=100), nullable=True),
    sa.Column('constituency', sa.String(length=200), nullable=True),
    sa.Column('parliament_term', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mps_chamber_term', 'mps', ['chamber', 'parliament_term'], unique=False)
    op.create_index('idx_mps_name', 'mps', ['name'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('chamber', sa.Enum('NATIONAL_ASSEMBLY', 'SENATE', name='chamberenum'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=True),
    sa.Column('sponsor_id', sa.UUID(), nullable=False),
    sa.Column('co_sponsor_ids', sa.JSON(), nullable=True),
    sa.Column('related_statement_ids', sa.JSON(), nullable=True),
    sa.Column('related_vote_ids', sa.JSON(), nullable=True),
    sa.Column('related_question_ids', sa.JSON(), nullable=True),
    sa.Column('related_petition_ids', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['mps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_number')
    )
    op.create_index('idx_bills_bill_number', 'bills', ['bill_number'], unique=False)
    op.create_index('idx_bills_chamber', 'bills', ['chamber'], unique=False)
    op.create_index('idx_bills_status', 'bills', ['status'], unique=False)
    op.create_table('petitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('petition_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('petitioner', sa.String(length=200), nullable=False),
    sa.Column('sponsor_id', sa.UUID(), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('chamber', sa.Enum('NATIONAL_ASSEMBLY', 'SENATE', name='chamberenum'), nullable=False),
    sa.Column('petition_text', sa.Text(), nullable=False),
    sa.Column('prayer', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('committee', sa.String(length=200), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('download_date', sa.DateTime(), nullable=False),
    sa.Column('vector_doc_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['mps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_petitions_date', 'petitions', ['submission_date'], unique=False)
    op.create_index('idx_petitions_sponsor_id', 'petitions', ['sponsor_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.String(length=50), nullable=False),
    sa.Column('asker_id', sa.UUID(), nullable=False),
    sa.Column('respondent_id', sa.UUID(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('question_date', sa.Date(), nullable=False),
    sa.Column('answer_date', sa.Date(), nullable=True),
    sa.Column('chamber', sa.Enum('NATIONAL_ASSEMBLY', 'SENATE', name='chamberenum'), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('ministry', sa.String(length=200), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('download_date', sa.DateTime(), nullable=False),
    sa.Column('vector_doc_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asker_id'], ['mps.id'], ),
    sa.ForeignKeyConstraint(['respondent_id'], ['mps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_asker_id', 'questions', ['asker_id'], unique=False)
    op.create_index('idx_questions_date', 'questions', ['question_date'], unique=False)
    op.create_table('statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('mp_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('vector_doc_id', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('related_bill_ids', sa.JSON(), nullable=True),
    sa.Column('related_question_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_statements_classification', 'statements', ['classification'], unique=False)
    op.create_index('idx_statements_document_id', 'statements', ['document_id'], unique=False)
    op.create_index('idx_statements_mp_id', 'statements', ['mp_id'], unique=False)
    op.create_table('bill_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('download_date', sa.DateTime(), nullable=False),
    sa.Column('vector_doc_id', sa.String(length=100), nullable=False),
    sa.Column('changes_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bill_versions_bill_id', 'bill_versions', ['bill_id'], unique=False)
    op.create_index('idx_bill_versions_version', 'bill_versions', ['bill_id', 'version_number'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('vote_date', sa.Date(), nullable=False),
    sa.Column('chamber', sa.Enum('NATIONAL_ASSEMBLY', 'SENATE', name='chamberenum'), nullable=False),
    sa.Column('vote_type', sa.String(length=50), nullable=False),
    sa.Column('ayes', sa.Integer(), nullable=True),
    sa.Column('noes', sa.Integer(), nullable=True),
    sa.Column('abstentions', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('download_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_votes_bill_id', 'votes', ['bill_id'], unique=False)
    op.create_index('idx_votes_date', 'votes', ['vote_date'], unique=False)
    op.create_table('mp_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vote_id', sa.UUID(), nullable=False),
    sa.Column('mp_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], ),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mp_votes_mp_id', 'mp_votes', ['mp_id'], unique=False)
    op.create_index('idx_mp_votes_vote_id', 'mp_votes', ['vote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mp_votes_vote_id', table_name='mp_votes')
    op.drop_index('idx_mp_votes_mp_id', table_name='mp_votes')
    op.drop_table('mp_votes')
    op.drop_index('idx_votes_date', table_name='votes')
    op.drop_index('idx_votes_bill_id', table_name='votes')
    op.drop_table('votes')
    op.drop_index('idx_bill_versions_version', table_name='bill_versions')
    op.drop_index('idx_bill_versions_bill_id', table_name='bill_versions')
    op.drop_table('bill_versions')
    op.drop_index('idx_statements_mp_id', table_name='statements')
    op.drop_index('idx_statements_document_id', table_name='statements')
    op.drop_index('idx_statements_classification', table_name='statements')
    op.drop_table('statements')
    op.drop_index('idx_questions_date', table_name='questions')
    op.drop_index('idx_questions_asker_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('idx_petitions_sponsor_id', table_name='petitions')
    op.drop_index('idx_petitions_date', table_name='petitions')
    op.drop_table('petitions')
    op.drop_index('idx_bills_status', table_name='bills')
    op.drop_index('idx_bills_chamber', table_name='bills')
    op.drop_index('idx_bills_bill_number', table_name='bills')
    op.drop_table('bills')
    op.drop_index('idx_mps_name', table_name='mps')
    op.drop_index('idx_mps_chamber_term', table_name='mps')
    op.drop_table('mps')
    op.drop_index('idx_documents_type_chamber_date', table_name='documents')
    op.drop_index('idx_documents_source_hash', table_name='documents')
    op.drop_index('idx_documents_date', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
