"""Add API usage tracking table

Revision ID: b7334d894ca2
Revises: bc0cea9ec17d
Create Date: 2026-01-30 17:40:26.140320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7334d894ca2'
down_revision = 'bc0cea9ec17d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_usage_date', 'api_usage', ['date'], unique=False)
    op.create_index('idx_api_usage_date_model', 'api_usage', ['date', 'model'], unique=False)
    op.create_index('idx_api_usage_model', 'api_usage', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_api_usage_model', table_name='api_usage')
    op.drop_index('idx_api_usage_date_model', table_name='api_usage')
    op.drop_index('idx_api_usage_date', table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
